[package]
name = "cellium-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
prost = { version = "0.12.6", features = ["prost-derive"] }
prost-build = "0.12.6"
walkdir = "2.5.0"
